apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "class-chat-bot.fullname" . }}
  labels:
    {{- include "class-chat-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "class-chat-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "class-chat-bot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "class-chat-bot.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          volumeMounts:
            {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            {{- end }}
            {{- if .Values.persistence.data.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.data.mountPath }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.config.existingClaim }}{{ .Values.persistence.config.existingClaim }}{{ else }}{{ include "class-chat-bot.fullname" . }}-config{{ end }}
        {{- end }}
        {{- if .Values.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.data.existingClaim }}{{ .Values.persistence.data.existingClaim }}{{ else }}{{ include "class-chat-bot.fullname" . }}-data{{ end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      envFrom:
        - secretRef:
            name: {{ include "class-chat-bot.fullname" . }}-env
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
