apiVersion: v1
kind: Secret
metadata:
  name: {{ include "class-chat-bot.fullname" . }}-env
  labels:
    {{- include "class-chat-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  DISCORD_TOKEN: {{ .Values.DISCORD_TOKEN | quote }}
  LLM_API_KEY: {{ .Values.LLM_API_KEY | quote }}
